apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ks-no.github.io
  title: KS Digital GitHub Pages
  description: >
    KS Digital sin GitHub Pages-nettside. Bruker source som default branch.
  annotations:
    github.com/project-slug: ks-no/ks-no.github.io
    backstage.io/techdocs-ref: dir:.
  tags:
    - github-pages
    - dokumentasjon
spec:
  type: tool
  owner: group:team-kjernekomponenter
  lifecycle: production
