@startuml
participant SAK as "Sak/Arkivsystem"
participant SvarUt
participant SDP as "Altinn/SDP"
actor innbygger as "Mottaker/Innbygger"
participant eDialog
SAK -> SvarUt : 1. SenderForsendelse med svar på forsendelse link
SvarUt --> SAK : 2. forsendelseid
SvarUt -> SDP : 3. Sender varsel med link
SDP -> innbygger: 4. klikker på link
innbygger -> eDialog : 5. Fyller ut skjema i edialog
eDialog --> innbygger : 6. Innbygger får kvittering på epost
SvarUt <- eDialog : 7. sender skjema til avsender
SAK <- SvarUt : 8. Mottar forsendelse via SvarInn
@enduml