skinparam {
    handwritten true
    backgroundcolor white
    DefaultFontName Avenir
}
skinparam state {
    FontName Impact
    BorderColor DarkGreen
    ArrowColor DarkGreen
    ArrowThickness 1
    BackgroundColor AliceBlue
 }
skinparam sequence {
    BorderColor DarkBlue
    ArrowColor DarkGreen
    ArrowThickness 1
    BackgroundColor AliceBlue
    LifeLineBorderColor DarkSlateGrey
    BoxBorderColor DarkGreen
}
skinparam note {
    FontName Avenir
    backgroundcolor white
    BorderColor DarkBlue
}
skinparam actor {
    FontName Impact
    BackgroundColor AliceBlue
    BorderColor DarkGreen
}
skinparam boundary {
    FontName Impact
    BackgroundColor AliceBlue
    BorderColor DarkGreen
}
skinparam entity {
    FontName Impact
    BackgroundColor AliceBlue
    BorderColor DarkGreen
}
skinparam participant {
    FontName Impact
    BackgroundColor AliceBlue
    BorderColor DarkGreen
}
skinparam control {
    FontName Impact
    BackgroundColor AliceBlue
    BorderColor DarkGreen
}

skinparam database {
    FontName Impact
    BackgroundColor AliceBlue
}

skinparam component {
    FontName Impact
    BorderColor DarkBlue
    BackgroundColor AliceBlue
}