@startgantt
Projectscale weekly
Project starts 2024-01-01

[Fiks Matrikkelføring] starts 2024-01-01
[Fiks Matrikkelføring] ends 2024-02-28
[Fiks Arkiv] starts 2024-01-01
[Fiks Arkiv] ends 2024-04-04
[Fiks Plan] starts 2024-01-01
[Fiks Plan] ends 2024-05-29
note bottom
  Planlagt ferdigstilt endelig versjon av protokollene
  Fiks Matrikkelføring, Fiks Arkiv og Fiks Plan.
end note
[Fiks Matrikkelføring] is colored in GreenYellow/Grey
[Fiks Arkiv] is colored in Pink/Grey
[Fiks Plan] is colored in LightBlue/Grey
@endgantt